services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ad
      POSTGRES_PASSWORD: ad
      POSTGRES_DB: ad
    volumes:
      - ad-pg-data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  ad-pg-data:
